#!/usr/bin/env python

import sys
import struct
import time
import asyncore
import socket
import logging
import json

logging.basicConfig(filename='/tmp/chrome.log',level=logging.DEBUG)

class PlayHandler(asyncore.dispatcher_with_send):

  # Handle incoming vim command
  def handle_read(self):
    data = self.recv(8192)
    if data:
      self.write_to_chrome(data)

      while 1:
        # Read the message type (first 4 bytes).
        text_length_bytes = sys.stdin.read(4)

        if len(text_length_bytes) > 0:
          # Read the message length (4 bytes).
          text_length = struct.unpack('i', text_length_bytes)[0]

          # Read the text (JSON object) of the message.
          text = sys.stdin.read(text_length)#.decode('utf-8')
          logging.debug("returned text " + text)

          self.send(text)
          self.close()
          return

        else:
          time.sleep(0.1)

  def write_to_chrome(self, command_text):
    formatted = { 'command': command_text.rstrip() }
    command = json.dumps(formatted).encode('utf-8')
    logging.debug("writing to chrome " + command)
    sys.stdout.write(struct.pack("I", len(command)))
    sys.stdout.write(command)
    sys.stdout.flush()


class PlayServer(asyncore.dispatcher):

  def __init__(self, host, port):
    asyncore.dispatcher.__init__(self)
    self.create_socket(socket.AF_INET, socket.SOCK_STREAM)
    self.set_reuse_addr()
    self.bind((host, port))
    self.listen(5)

  def handle_accept(self):
    pair = self.accept()
    if pair is not None:
      sock, addr = pair
      logging.debug("handling accept")
      handler = PlayHandler(sock)


if __name__ == '__main__':
  server = PlayServer('localhost', 8080)
  asyncore.loop()
