#!/usr/bin/env python

import sys
import struct
import time

def Main():
  message_number = 0

  while 1:
    # Read the message type (first 4 bytes).
    #text_length_bytes = sys.stdin.read(4)

    #if len(text_length_bytes) == 0:
      #break

    ## Read the message length (4 bytes).
    #text_length = struct.unpack('i', text_length_bytes)[0]

    ## Read the text (JSON object) of the message.
    #text = sys.stdin.read(text_length).decode('utf-8')

    message_number += 1

    response = '{"id": 1}'.encode('utf-8')

    try:
      sys.stdout.write(struct.pack("I", len(response)))
      sys.stdout.write(response)
      sys.stdout.flush()
      time.sleep(1)
    except IOError:
      break

if __name__ == '__main__':
  Main()
