#!/usr/bin/env python

import sys
import struct
import time
import asyncore
import socket
import logging
import json
import HTMLParser
import subprocess

logging.basicConfig(filename='/tmp/chrome.log',level=logging.DEBUG)

class PlayHandler(asyncore.dispatcher_with_send):

  # Handle incoming vim command
  def handle_read(self):
    data = self.recv(8192)
    if data:
      command_text = data.rstrip()

      if command_text in ['louder', 'softer']:
        self.handle_volume(command_text)

      self.write_to_chrome(command_text)

      # Wait for the response from the browser
      while 1:
        text_length_bytes = sys.stdin.read(4)

        if len(text_length_bytes) > 0:
          text_length = struct.unpack('i', text_length_bytes)[0]

          text = sys.stdin.read(text_length)
          formatted = self.format_song(text)

          self.send(formatted)
          self.close()
          return

        else:
          time.sleep(0.1)

  def handle_error(self):
    logging.exception("handled error")


  def handle_volume(self, command_text):
    amount = 20 # percent
    if command_text == 'softer':
      amount *= -1

    platform = sys.platform

    if platform == 'darwin':
      current_vol = subprocess.check_output(["osascript", '-e', 'output volume of (get volume settings)']).rstrip()
      new_vol = int(current_vol) * (100 + amount) / 100
      subprocess.call(["osascript", '-e', 'set volume output volume {}'.format(new_vol)])
    elif platform == 'win32':
      # no-op
      logging.debug("Windows :(")
    else:
      new_vol = "{}%".format(amount)
      subprocess.call(['pactl', 'set-sink-volume', '0', '--', new_vol])


  def write_to_chrome(self, command_text):
    formatted = { 'command': command_text }
    command = json.dumps(formatted).encode('utf-8')

    logging.debug("writing to chrome " + command)
    sys.stdout.write(struct.pack("I", len(command)))
    sys.stdout.write(command)
    sys.stdout.flush()

  def format_song(self, text):
    track_info = json.loads(text)['track']
    track = {key: track_info[key].encode('utf-8') for key in track_info.keys()}
    formatted = "{} - {}".format(track['artist'], track['song'])
    if track['album']:
      formatted += " / " + track['album']

    h = HTMLParser.HTMLParser()
    return h.unescape(formatted)

class PlayServer(asyncore.dispatcher):

  def __init__(self, host, port):
    asyncore.dispatcher.__init__(self)
    self.create_socket(socket.AF_INET, socket.SOCK_STREAM)
    self.set_reuse_addr()
    self.bind((host, port))
    self.listen(5)

  def handle_accept(self):
    pair = self.accept()
    if pair is not None:
      sock, addr = pair
      handler = PlayHandler(sock)


if __name__ == '__main__':
  try:
    server = PlayServer('localhost', 8123)
    asyncore.loop()
  except:
    logging.exception("global exception")
    raise
